<?php
/**
 * @file
 * A block module that displays a single version of an MVD at a time.
 * This is just a minimal wrapper for the object defined in mvdsingle.js
 */
function mvdsingle_preprocess_page()
{
    if ( strpos(request_uri(),"mvdsingle") )
    {
        drupal_add_css(drupal_get_path('module','mvdsingle')
            .'/css/mvdsingle.css','file');
        /* don't include javascript or it gets loaded twice */
    }
}
function mvdsingle_all()
{
    $mod_path = drupal_get_path('module', 'mvdsingle');
    $src = $mod_path.'/mvdsingle.js?target=content';
    if ( array_key_exists ("docid", $_GET) )
        $src .= '&docid='.$_GET["docid"];
    if ( array_key_exists ("version1", $_GET) )
        $src .= '&version1='.$_GET["version1"];
    if ( array_key_exists ("selections", $_GET) )
        $src .= '&selections='.$_GET["selections"];
    $html ='<script type="text/javascript" src="'.$src.'"></script>';
    return $html;
}
function mvdsingle_menu()
{
    $items = array();
    $items['admin/config/content/mvdsingle'] = array(
        'title'=>'mvdsingle',
        'description' => 'View an MVD one version at a time',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('mvdsingle_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['index'] = array(
        'title' => 'mvdsingle',
        'page callback' => 'mvdsingle_all',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}
/**
 * Implements hook_block_info().
 */
function mvdsingle_block_info() 
{
  $blocks['mvdsingle'] = array(
    'info' => t('Single MVD viewer'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
function mvdsingle_help($path, $arg) {
    switch ($path)
    {
        case "admin/help#mvdsingle":
            return '<p>' .
                t("View a multi-version document")
                . '</p>';
            break;
    }
}
/**
 * Implements hook_block_view(). Produces the contents of the block.
 * @param delta the name of the module
 * @return a key-value array
 */
function mvdsingle_block_view($delta = '') 
{
    switch ($delta) 
    {
        case 'mvdsingle':
	    $mod_path = drupal_get_path('module', 'mvdsingle');
            $args = 'target=content&docid='.$_GET["docid"]
                .'&version1='.$_GET["version1"];
            if ( array_key_exists('selections', $_GET) )
                $args .= '&selections='.$_GET['selections'];
            $block['content'] = '<script type="text/javascript" src="'
                .$mod_path.'/js/mvdsingle.js?'.$args.'"></script>';
            return $block;
    }
    // else there is nothing to do
}
/**
 * Page callback: Compare settings
 * @param form the form object to override
 * @param form_state the current state of the form (keys->values)
 * @return an updated form
 * @see quote_ticker_menu()
 */
function mvdsingle_form($form, &$form_state)
{
    $form['mvdsingle_docid'] = array(
        '#type' => 'textfield',
        '#title' => t('Default docid'),
        '#default_value' => 'english/harpur/h642',
        '#size' => 128,
        '#maxlength' => 256,
        '#required' => TRUE
    );
    return $form;
}

